import { Box, Button, Typography } from "@mui/material";
import { AppDispatch, RootState } from "../store/store";
import { useDispatch, useSelector } from "react-redux";
import { message } from 'antd';
import React, { useEffect, useState, useRef } from 'react';
import { removeSearch } from "../store/search-slice";

const SearchList: React.FC = () => {

  const { search } = useSelector((state: RootState) => state.search);
  
  const dispatch = useDispatch<AppDispatch>();

// 需要解决风控问题

// 保存前需要校验数据的完整性

// 暂停按钮出问题了

  const [Downloading, setDownloading] = useState(false);
  const [isCancelled, setIsCancelled] = useState(false); // Cancellation state
  
  
  const isCancelledRef = useRef(false); // Ref to track the cancellation state
  const [error, setError] = useState<string | null>(null);
  // 保存已完成的逻辑
  
  useEffect(() => {
    // 如果 songs 不为空，才执行保存操作
    if (search.length > 0) {
      const saveSearch = async () => {
        try {
          const updatedSearch = search.join("\n");
          await window.electronAPI.saveSearch(updatedSearch); // 使用 await 等待保存操作完成
        } catch (error) {
          console.error("Error saving songs:", error);
        }
      };
  
      saveSearch(); // 调用保存操作
    }
  }, [search]); // 依赖于 songs 更新
  
  // Whenever `isCancelled` changes, update the `isCancelledRef`
  useEffect(() => {
    isCancelledRef.current = isCancelled;
  }, [isCancelled]);

  // Handle search for a specific keyword and page
  // const handleSearch = async (keyword: string, page: number) => {

  //   try {
  //     const data = await window.electronAPI.getSearchVideo(keyword, page);


  //     await saveData(data, keyword, page);
      
  //     message.success(`视频搜索完成，第 ${page} 页`);
  //   } 
  //   catch (err) {
  //     message.error('获取视频数据失败');
  //   }
  // };

  // 修改 handleSearch为mock接口

  const handleSearch = async (keyword: string, page: number) => {

    // Mock 接口替代原本的 electronAPI 调用
    const mockGetSearchVideo = (keyword: string, page: number) => {
      return new Promise<any>((resolve, reject) => {
        setTimeout(() => {
          if (keyword && page > 0) {
            resolve({
              "code": 0,
              "message": "0",
              "ttl": 1,
              "data": {
                "seid": "9464764664854916746",
                "page": 1,
                "pagesize": 20,
                "numResults": 1000,
                "numPages": 50,
                "suggest_keyword": "",
                "rqt_type": "search",
                "cost_time": {
                  "total": "0.414438",
                  "fetch_lexicon": "0.002601",
                  "params_check": "0.002341",
                  "is_risk_query": "0.000184",
                  "illegal_handler": "0.000017",
                  "main_handler": "0.407811",
                  "as_request_format": "0.000540",
                  "as_request": "0.402852",
                  "deserialize_response": "0.000309",
                  "as_response_format": "0.003994"
                },
                "exp_list": {
                  "5512": true,
                  "6602": true,
                  "7708": true,
                  "9900": true,
                  "9924": true,
                  "9931": true,
                  "9943": true,
                  "9961": true,
                  "100010": true,
                  "100300": true,
                  "101500": true,
                  "101900": true,
                  "102405": true,
                  "102501": true,
                  "103006": true,
                  "103100": true,
                  "103201": true,
                  "103303": true,
                  "103400": true,
                  "103602": true,
                  "104101": true,
                  "104201": true,
                  "105104": true,
                  "105200": true,
                  "105404": true,
                  "105500": true,
                  "105803": true,
                  "106000": true,
                  "106207": true,
                  "106303": true,
                  "106403": true,
                  "106507": true,
                  "106707": true,
                  "106801": true,
                  "106902": true,
                  "107007": true,
                  "107104": true,
                  "107201": true,
                  "107400": true,
                  "107509": true,
                  "107603": true,
                  "107805": true,
                  "107900": true,
                  "108103": true,
                  "108402": true,
                  "171609": true,
                  "11074101": true,
                  "13440108": true,
                  "14356100": true,
                  "16028102": true,
                  "16289101": true,
                  "16966101": true,
                  "17281104": true,
                  "17784100": true
                },
                "egg_hit": 0,
                "result": [
                  {
                    "type": "video",
                    "id": 414447622,
                    "author": "weazegigi",
                    "mid": 454983428,
                    "typeid": "193",
                    "typename": "MV",
                    "arcurl": "http://www.bilibili.com/video/av414447622",
                    "aid": 414447622,
                    "bvid": "BV17V411S7DL",
                    "title": "Gigi Leung 梁咏琪 - <em class=\"keyword\">短发</em> （高清1080P修复MV）",
                    "description": "Gigi Leung 梁咏琪 - 短发 （高清1080P修复MV）\n选自 1997年 《 短发 》 专辑",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/1a443768a4a22f6fc2fc3d2f3adfd5e300ee673f.jpg",
                    "play": 284466,
                    "video_review": 356,
                    "favorites": 4929,
                    "tag": "华语MV,梁咏琪,短发,经典,高清修复,Gigi Leung",
                    "review": 259,
                    "pubdate": 1598622157,
                    "senddate": 1650886488,
                    "duration": "4:42",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "description",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 120000010,
                    "like": 3215,
                    "upic": "https://i2.hdslb.com/bfs/face/beccc07080f255f29478f9afd16b02ade195fbc0.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 356,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 1,
                    "rank_offset": 1,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 113684831535691,
                    "author": "JLRS-LeoFM",
                    "mid": 3493093607213343,
                    "typeid": "267",
                    "typename": "电台",
                    "arcurl": "http://www.bilibili.com/video/av113684831535691",
                    "aid": 113684831535691,
                    "bvid": "BV1gMkmYwEk5",
                    "title": "梁咏琪《<em class=\"keyword\">短发</em>》百万豪装录音棚大声听",
                    "description": "《短发》是由郑淑妃作词，陈国华作曲，梁咏琪演唱的歌曲，收录于梁咏琪1997年3月17日发行的音乐专辑《短发》中。\n\n录音设备：\n话筒：Neumann M149 tube Pair\n调音台：SSL Duality Delta Pro Station\n工作站：PT\n音箱：Barefoot MM12\n[侵删]",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/13eb1a0a0acb8cde5beec8261fe65e6b4ae2b19d.jpg",
                    "play": 89907,
                    "video_review": 17,
                    "favorites": 857,
                    "tag": "高音质,音响,短发,录音棚,梁咏琪,Hi-Fi,Hi-res,电台新星征集令,电台新星征集令4.0",
                    "review": 326,
                    "pubdate": 1734693502,
                    "senddate": 1734693502,
                    "duration": "4:44",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "description",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 115918641,
                    "like": 2251,
                    "upic": "https://i0.hdslb.com/bfs/face/a7176b4e205f2fae521faf3b6d22eca17a44e7a3.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 17,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 2,
                    "rank_offset": 2,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 361753288,
                    "author": "刘新宁在成都",
                    "mid": 3493078277032294,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av361753288",
                    "aid": 361753288,
                    "bvid": "BV1294y1e7fV",
                    "title": "减龄<em class=\"keyword\">短发</em>不翻车攻略",
                    "description": "可盐可甜，减龄，清爽短发",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/5ad7983958915bbdb3694cea8918e2b2d32f0656.jpg",
                    "play": 159417,
                    "video_review": 105,
                    "favorites": 9512,
                    "tag": "发型,短发,减龄",
                    "review": 400,
                    "pubdate": 1691207838,
                    "senddate": 1692891241,
                    "duration": "2:39",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "description",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 112341572,
                    "like": 6243,
                    "upic": "https://i1.hdslb.com/bfs/face/29f410d2a89f497af13484dcc2807aad04e3f673.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 105,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 3,
                    "rank_offset": 3,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 477835413,
                    "author": "咪咕视频",
                    "mid": 1086171925,
                    "typeid": "29",
                    "typename": "音乐现场",
                    "arcurl": "http://www.bilibili.com/video/av477835413",
                    "aid": 477835413,
                    "bvid": "BV1KK411y7Kw",
                    "title": "梁詠琪《<em class=\"keyword\">短发</em>》完整版，一开口就是整个难忘的青春年华～",
                    "description": "《时光音乐会2》单曲纯享版",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/63d338a668ff82bf7a5fa0d4c00e42790280d548.jpg",
                    "play": 883372,
                    "video_review": 995,
                    "favorites": 9112,
                    "tag": "完整版,短发,live,时光音乐会,梁咏琪,现场,经典老歌",
                    "review": 871,
                    "pubdate": 1673615420,
                    "senddate": 1673656993,
                    "duration": "3:57",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 109170596,
                    "like": 13589,
                    "upic": "https://i1.hdslb.com/bfs/face/12dbd4b459411fa647f978c697e78a2f4c3c8572.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 995,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 4,
                    "rank_offset": 4,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 615570217,
                    "author": "深圳帅芬",
                    "mid": 472141552,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av615570217",
                    "aid": 615570217,
                    "bvid": "BV1ih4y177Eg",
                    "title": "圆脸适合的<em class=\"keyword\">短发</em>❗️",
                    "description": "圆脸适合的短发❗️",
                    "arcrank": "0",
                    "pic": "//i0.hdslb.com/bfs/archive/a2a971afa40668612da40dcdfaba7559597cef1d.jpg",
                    "play": 414021,
                    "video_review": 291,
                    "favorites": 4201,
                    "tag": "圆脸,时尚好物种草,开启暑假的100种方式",
                    "review": 316,
                    "pubdate": 1688463117,
                    "senddate": 1688465291,
                    "duration": "4:3",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "description"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 108273899,
                    "like": 10271,
                    "upic": "https://i1.hdslb.com/bfs/face/2325684cafe17d4fb80691c5aa585fa170db7555.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 291,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 5,
                    "rank_offset": 5,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 47950687,
                    "author": "瑞一baby",
                    "mid": 171806259,
                    "typeid": "29",
                    "typename": "音乐现场",
                    "arcurl": "http://www.bilibili.com/video/av47950687",
                    "aid": 47950687,
                    "bvid": "BV1Ub411s7Lw",
                    "title": "张靓颖含泪翻唱《<em class=\"keyword\">短发</em>》很动情",
                    "description": "QQ音乐\n张靓颖含泪演唱，重新编曲",
                    "arcrank": "0",
                    "pic": "//i0.hdslb.com/bfs/archive/3bce79b856503323cb1ffffe2074f5e11703acd1.jpg",
                    "play": 1185012,
                    "video_review": 1577,
                    "favorites": 14234,
                    "tag": "张靓颖,华语现场,国语现场,歌曲,音乐现场",
                    "review": 555,
                    "pubdate": 1554082835,
                    "senddate": 1554082836,
                    "duration": "4:34",
                    "badgepay": false,
                    "hit_columns": [
                      "title"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 105909921,
                    "like": 17175,
                    "upic": "https://i0.hdslb.com/bfs/face/97bdbb86818f68c6a2fc376857cff8c877516117.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 1577,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 6,
                    "rank_offset": 6,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 1856330271,
                    "author": "米鸭鸭Mia",
                    "mid": 17880364,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av1856330271",
                    "aid": 1856330271,
                    "bvid": "BV1MW42197gS",
                    "title": "什么天选之人在靠剪<em class=\"keyword\">短发</em>变美啊？？？",
                    "description": "-",
                    "arcrank": "0",
                    "pic": "//i0.hdslb.com/bfs/archive/cf98cadb1d71f5a1b4c259d5b31ab6ff02dfaab3.jpg",
                    "play": 219399,
                    "video_review": 212,
                    "favorites": 2342,
                    "tag": "发型,短发,普通人变美指南,夏日时髦地图",
                    "review": 357,
                    "pubdate": 1722335400,
                    "senddate": 1728530477,
                    "duration": "2:33",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 104575474,
                    "like": 8782,
                    "upic": "https://i1.hdslb.com/bfs/face/d71495053c76645fc5caad98dd0b82174d2d1c06.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 212,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 7,
                    "rank_offset": 7,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 725688541,
                    "author": "发型师诺曼",
                    "mid": 1113825985,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av725688541",
                    "aid": 725688541,
                    "bvid": "BV1iS4y1Y7nQ",
                    "title": "简约男士<em class=\"keyword\">短发</em>教程，重点是掌握这三个步骤",
                    "description": "三个步骤学会简易男士短发",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/449d20471bd2c6f0bd07b3e8576954156b4de85b.jpg",
                    "play": 92355,
                    "video_review": 156,
                    "favorites": 3881,
                    "tag": "跟着B站UP主学化妆,春日发型分享,日常,分享,发型,教程,剪发,美发,发型师,男士发型,发型设计",
                    "review": 167,
                    "pubdate": 1649909460,
                    "senddate": 1673425927,
                    "duration": "10:35",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "description"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103565475,
                    "like": 2518,
                    "upic": "https://i1.hdslb.com/bfs/face/5575a22b65216b4c1042b0af8115ec572f7d16b9.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 156,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 8,
                    "rank_offset": 8,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 431865152,
                    "author": "杭州简华男士发型火火",
                    "mid": 1661881841,
                    "typeid": "252",
                    "typename": "仿妆cos",
                    "arcurl": "http://www.bilibili.com/video/av431865152",
                    "aid": 431865152,
                    "bvid": "BV1rG411L7xf",
                    "title": "男生<em class=\"keyword\">短发</em>看这十三款就够了",
                    "description": "-",
                    "arcrank": "0",
                    "pic": "//i2.hdslb.com/bfs/archive/387b223a20a36d864abb7a0ef1dd5ef52eff3032.jpg",
                    "play": 164504,
                    "video_review": 32,
                    "favorites": 1735,
                    "tag": "男生,男生发型,发型,男士发型,短发,美妆",
                    "review": 28,
                    "pubdate": 1666259614,
                    "senddate": 1666259614,
                    "duration": "1:47",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103421472,
                    "like": 1428,
                    "upic": "https://i2.hdslb.com/bfs/face/61c73d2e69cc90583e34b8b5ead4656866b1ea07.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 32,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 9,
                    "rank_offset": 9,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 269553546,
                    "author": "造型师star星星",
                    "mid": 505284566,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av269553546",
                    "aid": 269553546,
                    "bvid": "BV1Jc411W71N",
                    "title": "女生头发一至30厘米最好看的18款<em class=\"keyword\">短发</em>",
                    "description": "-",
                    "arcrank": "0",
                    "pic": "//i2.hdslb.com/bfs/archive/26f601b778303c326a56571e958a9c65cfbddae5.jpg",
                    "play": 356524,
                    "video_review": 337,
                    "favorites": 8789,
                    "tag": "发型,短发",
                    "review": 222,
                    "pubdate": 1680591589,
                    "senddate": 1680621493,
                    "duration": "3:8",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103280581,
                    "like": 8055,
                    "upic": "https://i2.hdslb.com/bfs/face/bb966c7cf5f72848351c15cf88b63e617933650b.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 337,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 10,
                    "rank_offset": 10,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 1305530658,
                    "author": "你好萝卜HDMusic",
                    "mid": 2071778929,
                    "typeid": "29",
                    "typename": "音乐现场",
                    "arcurl": "http://www.bilibili.com/video/av1305530658",
                    "aid": 1305530658,
                    "bvid": "BV1vM4m1U7p8",
                    "title": "梁咏琪&amp;陈楚生《<em class=\"keyword\">短发</em>》2024/6/14.天赐5高清源码",
                    "description": "梁咏琪&amp;陈楚生",
                    "arcrank": "0",
                    "pic": "//i2.hdslb.com/bfs/archive/6d06d9e288a757f3d41c5b47816090cfb235256b.jpg",
                    "play": 80889,
                    "video_review": 270,
                    "favorites": 726,
                    "tag": "陈楚生,梁咏琪",
                    "review": 61,
                    "pubdate": 1718380219,
                    "senddate": 1718380280,
                    "duration": "4:5",
                    "badgepay": false,
                    "hit_columns": [
                      "title"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103229221,
                    "like": 1058,
                    "upic": "https://i1.hdslb.com/bfs/face/dc123a3c9b5902f9aa8f803d031bec25fb3bc496.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 270,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 11,
                    "rank_offset": 11,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 466258015,
                    "author": "四不像的迷鹿",
                    "mid": 34399948,
                    "typeid": "21",
                    "typename": "日常",
                    "arcurl": "http://www.bilibili.com/video/av466258015",
                    "aid": 466258015,
                    "bvid": "BV1u5411f7Qq",
                    "title": "短 发 天 花 板",
                    "description": "bgm：有点甜~",
                    "arcrank": "0",
                    "pic": "//i0.hdslb.com/bfs/archive/2530aa2a7102f6b26ed6b8803516ac2045f0ddfd.jpg",
                    "play": 2499636,
                    "video_review": 6330,
                    "favorites": 62368,
                    "tag": "萌妹子,可爱,美女,纯欲,短发,小姐姐,青春,颜值",
                    "review": 2427,
                    "pubdate": 1644252335,
                    "senddate": 1645239962,
                    "duration": "1:48",
                    "badgepay": false,
                    "hit_columns": [
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103206743,
                    "like": 167521,
                    "upic": "https://i1.hdslb.com/bfs/face/28c16885cc363efd1aa91cf7e16f518d2b3607b7.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 6330,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 12,
                    "rank_offset": 12,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 684126182,
                    "author": "智慧芒果呀",
                    "mid": 1246320345,
                    "typeid": "242",
                    "typename": "娱乐粉丝创作",
                    "arcurl": "http://www.bilibili.com/video/av684126182",
                    "aid": 684126182,
                    "bvid": "BV16U4y1m7ti",
                    "title": "【李知恩】<em class=\"keyword\">短发</em>合集",
                    "description": "【李知恩】短发合集",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/5bb8a0ff1f771bc2e204e8d2328e48b714452d19.jpg",
                    "play": 355516,
                    "video_review": 208,
                    "favorites": 4728,
                    "tag": "星动安利大作战,IU,李知恩,神颜,女神,爱豆",
                    "review": 132,
                    "pubdate": 1652773795,
                    "senddate": 1655825380,
                    "duration": "2:32",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "description"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103160133,
                    "like": 9159,
                    "upic": "https://i0.hdslb.com/bfs/face/c130cf61425e96a116b300f0b53c76c14990d583.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 208,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 13,
                    "rank_offset": 13,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 534906516,
                    "author": "武汉发型师秦忆",
                    "mid": 162633236,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av534906516",
                    "aid": 534906516,
                    "bvid": "BV1fM41197X8",
                    "title": "让托尼老师反复看完的同款<em class=\"keyword\">短发</em>教程",
                    "description": "减龄短发",
                    "arcrank": "0",
                    "pic": "//i2.hdslb.com/bfs/archive/9a1ac1f5af89df5edc24603e8dbd202d7fae3a7d.jpg",
                    "play": 27619,
                    "video_review": 5,
                    "favorites": 765,
                    "tag": "教程,老师,发型,短发,托尼,美妆",
                    "review": 47,
                    "pubdate": 1697899313,
                    "senddate": 1700018831,
                    "duration": "2:16",
                    "badgepay": false,
                    "hit_columns": [],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103107480,
                    "like": 383,
                    "upic": "https://i2.hdslb.com/bfs/face/a10bcccc47ef9e4010530fd71648d051d980ff3b.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 5,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 14,
                    "rank_offset": 14,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 113678288421429,
                    "author": "深圳发型设计明羽",
                    "mid": 3493121956514142,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av113678288421429",
                    "aid": 113678288421429,
                    "bvid": "BV17UkgYuEjE",
                    "title": "方圆脸、圆脸女生把头发剪短后，瞬间年轻了十岁！",
                    "description": "-",
                    "arcrank": "0",
                    "pic": "//i0.hdslb.com/bfs/archive/92bd62b76ee2594aade1124800e599abb74dd051.jpg",
                    "play": 628,
                    "video_review": 0,
                    "favorites": 8,
                    "tag": "发型,圆脸,美妆,减龄短发,方圆脸,换个发型换个人,普通人变美指南,让你笑着走出这个理发店,跨越千年，从”头“看时尚",
                    "review": 4,
                    "pubdate": 1734600300,
                    "senddate": 1734600301,
                    "duration": "1:40",
                    "badgepay": false,
                    "hit_columns": [],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 103047362,
                    "like": 8,
                    "upic": "https://i0.hdslb.com/bfs/face/aeee7a2681cec9edc651c52898e73bb5b3fe879f.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 0,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 15,
                    "rank_offset": 15,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 113049679693079,
                    "author": "必成高富帅",
                    "mid": 36228849,
                    "typeid": "263",
                    "typename": "颜值安利",
                    "arcurl": "http://www.bilibili.com/video/av113049679693079",
                    "aid": 113049679693079,
                    "bvid": "BV1QHH5e6E9n",
                    "title": "近些年来，我们追过的【<em class=\"keyword\">短发</em>】业界老师（合集）",
                    "description": "希岛爱里\n君岛美绪 \n凉森玲梦\n椎名空\n葵司\n翼舞\n石原希望 \nMinamo\n水野朝阳\n向井蓝\n奥田咲\n纱仓真菜\n里美尤利娅\n希美真由\n唯井真寻\n麻里梨夏\n铃村爱里\n阿部乃美久\n深田咏美\n户田真琴\n夏目响 \n水卜樱\n宍戸里帆\n松本菜奈实  \n凑莉久\n柊优希\n深田结梨\n月乃露娜\n推川悠里\n滨崎真緒\n乙爱丽丝\n三宫椿\n梦实香苗\n本庄优花\n小岩伊都\n麻仓优\n埴生御子\n铃木心春\n西元明沙\n松冈千菜\n日向夏\n神小泉彩  \n筱田优\n星乃莉子\n葵伊吹\n入田真绫\n水谷梨明日\n美乃雀\n本乡爱",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/3cb15dd4461b880a3deeee81de03237a6d06cdc1.jpg",
                    "play": 20815,
                    "video_review": 55,
                    "favorites": 787,
                    "tag": "可爱,美女,偶像,女神,明星,写真,模特,盘点,颜值,我的追星日记,全能追星企划6.0",
                    "review": 69,
                    "pubdate": 1725002396,
                    "senddate": 1725002397,
                    "duration": "9:27",
                    "badgepay": false,
                    "hit_columns": [
                      "title"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 102981085,
                    "like": 357,
                    "upic": "https://i0.hdslb.com/bfs/face/edabf43aa0c6ebe0a1b65899fb265f72b5c3b7de.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 55,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 16,
                    "rank_offset": 16,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 113680100363021,
                    "author": "广州主打减龄发型沈永",
                    "mid": 357093647,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av113680100363021",
                    "aid": 113680100363021,
                    "bvid": "BV1YNkBYGExb",
                    "title": "适合所有女生剪短不用打理的挂耳<em class=\"keyword\">短发</em>",
                    "description": "适合所有女生剪短不用打理的挂耳短发",
                    "arcrank": "0",
                    "pic": "//i2.hdslb.com/bfs/archive/0e0aac787f9f47a54870e9f9592517fd05ad034f.jpg",
                    "play": 2333,
                    "video_review": 0,
                    "favorites": 26,
                    "tag": "女生,发型,短发,发型教程,烫发,如何度过短发尴尬期,宝妈短发",
                    "review": 3,
                    "pubdate": 1734620814,
                    "senddate": 1734620815,
                    "duration": "2:47",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "description",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 102914582,
                    "like": 59,
                    "upic": "https://i2.hdslb.com/bfs/face/335effb9de42f86a0195ce1e21492987645cc090.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 0,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 17,
                    "rank_offset": 17,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 975876254,
                    "author": "天娇小姐姐",
                    "mid": 337848524,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av975876254",
                    "aid": 975876254,
                    "bvid": "BV1p44y1t7MB",
                    "title": "拒绝土气！3个技巧学会打理日系女主角<em class=\"keyword\">短发</em>",
                    "description": "超级简单又实用！\n往期还有更多发型技巧，点点关注哟",
                    "arcrank": "0",
                    "pic": "//i2.hdslb.com/bfs/archive/dd8c65fbe77e9bc100aa00b262e5882a4aba920b.jpg",
                    "play": 178503,
                    "video_review": 267,
                    "favorites": 7702,
                    "tag": "我今天真好看,美妆,学生党,发型,初秋发型,短发,日系短发,八字刘海,发型教程,变美",
                    "review": 206,
                    "pubdate": 1633435162,
                    "senddate": 1676443106,
                    "duration": "3:50",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 102895180,
                    "like": 6580,
                    "upic": "https://i2.hdslb.com/bfs/face/07c15e7dbc5c0fd8995a056b470ab16e59987a28.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 267,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 18,
                    "rank_offset": 18,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 944447621,
                    "author": "成铭聊时尚",
                    "mid": 651545926,
                    "typeid": "159",
                    "typename": "时尚潮流",
                    "arcurl": "http://www.bilibili.com/video/av944447621",
                    "aid": 944447621,
                    "bvid": "BV1mW4y1E7rd",
                    "title": "剪完不会后悔的10种爆款<em class=\"keyword\">短发</em>，时尚减龄又显脸小，每一种都好看",
                    "description": "这十种短发都是很流行的爆款，也是人气很旺的网红款发型：1、露眉式；2、不等式；3、狗啃式；4、鲻鱼头；5、碎盖头；6、短碎式；7、挂耳式；8、妹妹头；9、狼尾式；10、初恋头。这十种短发，每一种都非常好看，时尚减龄又显脸小，简单随意又好打理。",
                    "arcrank": "0",
                    "pic": "//i0.hdslb.com/bfs/archive/03bdc85823e3ca5dcf1166935f50744c653623ed.jpg",
                    "play": 5953,
                    "video_review": 1,
                    "favorites": 65,
                    "tag": "眉上短刘海,狗啃式,鲻鱼头,波波头,初恋头,短发发型,流行发型,流行短发,狼尾式",
                    "review": 0,
                    "pubdate": 1666623206,
                    "senddate": 1666623206,
                    "duration": "3:58",
                    "badgepay": false,
                    "hit_columns": [],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 102684116,
                    "like": 32,
                    "upic": "https://i1.hdslb.com/bfs/face/90a8b22b1588e66895d69cc72ebf84b550924931.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 1,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 19,
                    "rank_offset": 19,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  },
                  {
                    "type": "video",
                    "id": 941323325,
                    "author": "桃心六六子",
                    "mid": 2620929,
                    "typeid": "157",
                    "typename": "美妆护肤",
                    "arcurl": "http://www.bilibili.com/video/av941323325",
                    "aid": 941323325,
                    "bvid": "BV1iW4y127E5",
                    "title": "自己在家就能剪的<em class=\"keyword\">短发</em>，和tony说拜拜！",
                    "description": "Bgm\n lemon tree\nReplay（姐姐真漂亮）",
                    "arcrank": "0",
                    "pic": "//i1.hdslb.com/bfs/archive/f81c7a705db572f07643f321ad5a1373f69df6c5.jpg",
                    "play": 255017,
                    "video_review": 142,
                    "favorites": 8445,
                    "tag": "夏日时尚大改造,短发,剪发,发型,发型教程",
                    "review": 168,
                    "pubdate": 1658666400,
                    "senddate": 1676395004,
                    "duration": "2:41",
                    "badgepay": false,
                    "hit_columns": [
                      "title",
                      "tag"
                    ],
                    "view_type": "",
                    "is_pay": 0,
                    "is_union_video": 0,
                    "rec_tags": null,
                    "new_rec_tags": [],
                    "rank_score": 102637713,
                    "like": 7209,
                    "upic": "https://i0.hdslb.com/bfs/face/4507960a7039ffd4d86c6a125766144522dabae3.jpg",
                    "corner": "",
                    "cover": "",
                    "desc": "",
                    "url": "",
                    "rec_reason": "",
                    "danmaku": 142,
                    "biz_data": null,
                    "is_charge_video": 0,
                    "vt": 0,
                    "enable_vt": 0,
                    "vt_display": "",
                    "subtitle": "",
                    "episode_count_text": "",
                    "release_status": 0,
                    "is_intervene": 0,
                    "area": 0,
                    "style": 0,
                    "cate_name": "",
                    "is_live_room_inline": 0,
                    "live_status": 0,
                    "live_time": "",
                    "online": 0,
                    "rank_index": 20,
                    "rank_offset": 20,
                    "roomid": 0,
                    "short_id": 0,
                    "spread_id": 0,
                    "tags": "",
                    "uface": "",
                    "uid": 0,
                    "uname": "",
                    "user_cover": "",
                    "parent_area_id": 0,
                    "parent_area_name": "",
                    "watched_show": null
                  }
                ],
                "show_column": 0,
                "in_black_key": 0,
                "in_white_key": 0
              }
            });
          } else {
            reject('Invalid keyword or page');
          }
        }, 1000); // 模拟请求延时
      });
    };
  
    try {
      // 使用 mock 接口代替原本的 API 调用
      const data = await mockGetSearchVideo(keyword, page);
    const bvids = data.data.result.map((video: any) => video.bvid);
    await saveData(data, keyword, page);
    bvids.forEach((bvid: any) => {
      // 在这里应用你的函数，比如：
      console.log(`Applying function to bvid: ${bvid}`);


      
      // 你可以在这里调用一个自定义的函数
    });


      // await saveData(data, keyword, page);
      
      message.success(`视频搜索完成，第 ${page} 页`);
    } catch (err) {
      message.error('获取视频数据失败');
    }
  };
  
  
  

  // Save data to local
  // const saveData = async (data: any, keyword: string, page: number) => {
  //   try {
  //     const pageString = `${keyword}_ ${page}`;
  //     const result = await window.electronAPI.saveSearchResult(data, keyword, pageString);

  //     if (result.success) {
  //       message.success(`数据已保存到: ${result.path}`);
  //     } else {
  //       throw new Error(result.error);
  //     }
  //   } catch (err: any) {
  //     message.error(`保存数据失败: ${err.message}`);
  //   }
  // };


  // 先修改为Mock接口

  const saveData = async (data: any, keyword: string, page: number) => {
    try {
      const pageString = `${keyword}_ ${page}`;


      const result = await window.electronAPI.saveSearchResultMock(data, keyword, pageString);

      if (result.success) {
        message.success(`数据已保存到: ${result.path}`);
      } else {
        throw new Error(result.error);
      }
    } catch (err: any) {
      message.error(`保存数据失败: ${err.message}`);
    }
  };


  // DeepBulkSearch: Process each search result one by one
  const deepBulkSearch = async () => {
  
    if (!search.length) {
      message.error('没有搜索结果');
      return;
    }

    setDownloading(true); // Set loading state when the search begins
   
   
    setIsCancelled(false); // Reset cancellation state

    try {
      // Process each search result
      for (let i = 0; i < search.length; i++) {
        // Check if the operation is cancelled
        if (isCancelledRef.current) {
          setDownloading(false); // 恢复按钮的可点击状态

          message.info('操作已取消2');
          
          setIsCancelled(false); // Reset cancellation state

          return;
        }

        const result = search[i];
        if (!result) {
          message.error(`没有找到关键词: 第 ${i + 1} 条`);
          
          dispatch(removeSearch({ id: result }));
        
          continue;
        
        }
        
        for (let page = 1; page <= 50; page++) {

          if (isCancelledRef.current) {
            setDownloading(false); // 恢复按钮的可点击状态
  
            message.info('操作已取消，关键词保留');
            
            setIsCancelled(false); // Reset cancellation state
  
            return;
          }
          await handleSearch(result, page); // Assuming only one page is handled per result
        
        }
  
        // Start searching for the specific result
       

        // Remove processed search from the state
        dispatch(removeSearch({ id: result }));
      }

      message.success('所有数据已成功保存并删除');
    } catch (err) {
      setError('批量搜索失败');
      message.error('批量搜索失败');
    } finally {
      setDownloading(false);
    }
  };

  // Toggle the cancel button
  const handleCancel = () => {
    setIsCancelled((prev) => !prev);
  };

  return (
    <Box>
      <Typography variant="h6">
        Search Length: {search.length}
      </Typography>

      {/* Trigger deep bulk search */}
      {/* <Button 
        variant="contained" 
        color="primary" 
        onClick={deepBulkSearch} 
        disabled={Downloading}
        style={{ marginTop: 20 }}
      >
        Deep Bulk Search (逐条处理)
      </Button> */}

      {/* Cancel button to stop the operation */}
      {/* <Button 
        variant="contained" 
        color="secondary" 
        onClick={handleCancel} 
        disabled={!Downloading} 
        style={{ marginTop: 20, marginLeft: 10 }}
      >
        {isCancelled ? '已取消' : '取消操作'}
      </Button> */}
    <Button
      variant="contained"
      color="primary"
      onClick={() => handleSearch('短发', 1)} // 使用匿名函数
      sx={{ marginTop: '16px' }}
    >
      搜索
    </Button>

      {/* Display error message */}
      {error && <Typography color="error" variant="body2" style={{ marginTop: 20 }}>{error}</Typography>}
    </Box>
  );
};

export default SearchList;
